// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OcrWebService.Data;

#nullable disable

namespace OcrWebService.Migrations
{
    [DbContext(typeof(DbFileContext))]
    partial class DbFileContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.26");

            modelBuilder.Entity("OcrWebService.Data.Entity.OcrResultEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BlobId")
                        .HasColumnType("TEXT");

                    b.Property<float?>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<string>("InputExtension")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputExtension")
                        .HasColumnType("TEXT");

                    b.Property<long?>("Size")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("OcrResults");
                });
#pragma warning restore 612, 618
        }
    }
}
